plugins {
    id 'java'
    alias(libs.plugins.shadow)
}

allprojects {
    apply plugin: 'java'

    // group & version come from gradle.properties

    repositories {
        mavenCentral()
        maven { url = "https://oss.sonatype.org/content/repositories/snapshots/" }
        maven { url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/" }
        maven { url = "https://libraries.minecraft.net/" }
        maven {
            url = "https://jitpack.io"
            content {
                excludeGroup "fr.milekat"
            }
        }
        maven { url = "https://repo.ranull.com/maven/external/" }
        maven {
            name = 'papermc'
            url = 'https://repo.papermc.io/repository/maven-public/'
        }
        maven {
            url = uri("https://maven.pkg.github.com/m1lekat/MilekatUtils")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
        maven {
            url = uri("https://maven.pkg.github.com/m1lekat/MileNpc")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
        maven { url = "https://repo.fancyplugins.de/releases" }
    }

    dependencies {
        //  Annotation
        compileOnly libs.jetbrains.annotations

        //  Minecraft
        compileOnly libs.paper.api
    }

    tasks.withType(JavaCompile).configureEach {
        options.release = (project.findProperty('javaVersion') as String).toInteger()
    }

    processResources {
        filesMatching('plugin.yml') {
            expand(
                    'pluginName'          : rootProject.name,
                    'pluginVersion'       : project.version,
                    'pluginAuthor'        : project.findProperty('pluginAuthor'),
                    'pluginMain'          : project.findProperty('mainClass'),
                    'pluginApiVersion'    : project.findProperty('apiVersion'),
                    'pluginDescription'   : project.findProperty('projectDescription'),
                    'githubOwner'         : project.findProperty('githubOwner'),
                    'githubRepository'    : project.findProperty('githubRepository'),
                    'milekatUtilsVersion' : libs.versions.milekatUtils.get(),
                    'jacksonVersion'      : libs.versions.jackson.get(),
                    'elasticsearchVersion': libs.versions.elasticsearch.get()
            )
        }
    }
}

jar {
    from('src/main/java') {
        include "fr/milekat/shop/storage/adapter/sql/shop_schema.sql"
    }
    actions = [] as List<Action<? super Task>>
    dependsOn('shadowJar')
}

shadowJar {
    getArchiveClassifier().set(null)

    relocate 'fr.mrmicky' , 'fr.milekat.shops.libs.fastinv'
}

dependencies {
    implementation project('mile-shops-api')

    //  Milekat
    compileOnly libs.mile.npc.api
    compileOnly libs.mile.banks.api

    //  Utils
    compileOnly libs.milekat.utils
    implementation libs.fastinv

    //  Storage clients
    compileOnly libs.hikaricp
    compileOnly libs.mysql.connector
    compileOnly libs.mariadb.client
    compileOnly libs.postgresql

    compileOnly libs.jackson.core
    compileOnly libs.jackson.databind
    compileOnly libs.jackson.yaml
    compileOnly libs.elasticsearch.java
}
