# Project metadata (centralized)
group=fr.milekat
version=1.5.0-SNAPSHOT

projectName=MileShops
projectDescription=API/Plugin to create trading shops
mainClass=fr.milekat.shops.Main
javaVersion=25
apiVersion=26.1

authorId=milekat
authorName=arthur
authorEmail=arthur@milekat.fr
pluginAuthor=MileKat

githubOwner=m1lekat
githubRepository=MileShops
license=MIT License
licenseUrl=https://opensource.org/licenses/MIT
