name: ${pluginName}
author: ${pluginAuthor}
main: ${pluginMain}
version: ${pluginVersion}
api-version: '${pluginApiVersion}'
description: "${pluginDescription}"
website: https://github.com/${githubOwner}/${githubRepository}
softdepend:
  - MileNpc
  - MileBanks
libraries:
  # Utils
  - fr.milekat:milekat-utils:${milekatUtilsVersion}
  - com.fasterxml.jackson.core:jackson-databind:${jacksonVersion}
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:${jacksonVersion}
  # Storage
  - co.elastic.clients:elasticsearch-java:${elasticsearchVersion}
commands:
  shop:
    description: "Command to manage shops"
    permission: "shops.command"
    permission-message: "You can't perform this command"
permissions:
  shops.create:
    description: "Permission to create shops"
    default: op
  shops.edit:
    description: "Permission to edit shops"
    default: op
  shop.reload:
    description: "Permission to reload the plugin and the shops"
    default: op
  shop.remove:
    description: "Permission to remove shops"
    default: op