plugins {
    id 'java'
    id 'maven-publish'
    id 'signing'
}

java {
    withJavadocJar()
    withSourcesJar()
}

// Force character encoding
tasks.withType(Javadoc).configureEach {
    options.encoding = 'UTF-8'
    options.tags = [ "apiNote", "implNote", "implSpec" ]
}

def githubUrl = "https://github.com/${githubOwner}/${githubRepository}"

publishing {
    publications {
        maven(MavenPublication) {
            artifactId = 'mile-shops-api'
            from components.java

            pom {
                name = "${rootProject.name}API"
                description = "API for ${rootProject.name} plugin"
                url = githubUrl

                licenses {
                    license {
                        name = findProperty('license')
                        url = findProperty('licenseUrl')
                    }
                }

                developers {
                    developer {
                        id = findProperty('authorId')
                        name = findProperty('authorName')
                        email = findProperty('authorEmail')
                    }
                }

                scm {
                    connection = "scm:git:git://github.com/${githubOwner}/${githubRepository}.git"
                    developerConnection = "scm:git:ssh://github.com/${githubOwner}/${githubRepository}.git"
                    url = githubUrl
                }
            }
        }
    }

    repositories {
        maven {
            name = "GitHubPackages"
            url = uri("https://maven.pkg.github.com/${githubOwner}/${githubRepository}")
            credentials {
                username = project.findProperty("gpr.user") ?: System.getenv("USERNAME")
                password = project.findProperty("gpr.key") ?: System.getenv("TOKEN")
            }
        }
        maven {
            name = "StagingDeploy"
            url = layout.buildDirectory.dir('staging-deploy')
        }
    }
}

signing {
    // Only apply signing when it's not a snapshot version
    if (!version.endsWith('SNAPSHOT')) {
        sign publishing.publications
    }
}